final_proj/models.py
from final_proj import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)
    nickname = db.Column(db.String(36), unique=True, nullable=False)

final_proj/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, EqualTo, ValidationError
from final_proj.models import User

class RegisterForm(FlaskForm):
    username = StringField('아이디', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('비밀번호', validators=[DataRequired(), EqualTo('confirm_password', message='비밀번호가 일치하지 않습니다')])
    confirm_password = PasswordField('비밀번호 확인', validators=[DataRequired()])
    nickname = StringField('닉네임', validators=[DataRequired(), Length(min=2, max=20)])
    submit = SubmitField('회원가입')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('이미 존재하는 아이디입니다.')

    def validate_nickname(self, nickname):
        user = User.query.filter_by(nickname=nickname.data).first()
        if user:
            raise ValidationError('이미 존재하는 닉네임입니다.')

class LoginForm(FlaskForm):
    username = StringField('아이디', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('비밀번호', validators=[DataRequired()])
    submit = SubmitField('로그인')

final_proj/__init__.py
from flask import Flask, g
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import final_proj.config as config

# db객체를 create_app 함수 안에서 생성하면 블루프린트와 같은 다른 모듈에서 사용할 수 없으므로 db, migrate는 create_app 함수 밖에서 생성
db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__) # 플라스크 어플리케이션 생성
    app.config.from_object(config.Config)

    # ORM
    db.init_app(app) # 함수 밖에서 생성한 객체를 앱에 등록
    migrate.init_app(app, db)
    from . import models

    # 블루프린트
    from .views import main_views, auth_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(auth_views.bp)

    # 로그인 정보 불러오기
    @app.context_processor
    def inject_user():
        return dict(user=g.user)

    return app

final_proj/views/auth_views.py
# 참고: https://wikidocs.net/81057
from flask import Blueprint, url_for, render_template, request, session, g, jsonify
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
from functools import wraps

from final_proj import db
from final_proj.forms import RegisterForm, LoginForm
from final_proj.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/register/', methods=('GET', 'POST'))
def register():
    form = RegisterForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        
        # db에 유저가 없으면
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password.data), # pw를 해시 형태로 변환
                        nickname=form.nickname.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))
        else:
            print('이미 존재하는 사용자입니다.')
    return render_template('registration.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            error = None
            user = User.query.filter_by(username=form.username.data).first()
            if not user:
                error = "존재하지 않는 사용자입니다."
            elif not check_password_hash(user.password, form.password.data):
                error = "비밀번호가 올바르지 않습니다."
            
            if error is None:
                session.clear()
                session['user_id'] = user.id
                return jsonify({'success': True, 'message':'로그인 성공'})
            else:
                return jsonify({'success': False, 'message': error})
        else:
            return jsonify({'success': False, 'message': '제출 폼이 유효하지 않습니다.'})
    elif request.method == 'GET':
        return render_template('login.html', form=form)
    else:
        return jsonify({'success': False, 'message': 'Invalid request method'})
    
# 로그인 여부 확인
@bp.before_app_request
def is_login():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

# 로그인 되지 않았을 경우 로그인 페이지로 이동
# 데코레이터: 다른 함수를 인자로 받아, 그 함수에 새로운 기능을 덧붙여서 이를 반환하는 함수
def login_required(view):
    @wraps(view)
    def wrapped_view(**kwargs): # 함수가 호출될 때 제공된 모든 키워드 인자를 캡처하여 함수 내에서 딕셔너리로 접근
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

@bp.route('/logout/')
def logout():
    session.clear()
    print('로그아웃 완료')
    return redirect(url_for('auth.login'))

# username, nickname 중복 검사
@bp.route('/check/username', methods=['POST'])
def check_username():
    username = request.json.get('username')
    user = User.query.filter_by(username=username).first()
    return jsonify({'exists': bool(user)})

@bp.route('/check/nickname', methods=['POST'])
def check_nickname():
    nickname = request.json.get('nickname')
    user = User.query.filter_by(nickname=nickname).first()
    return jsonify({'exists': bool(user)})

final_proj/views/main_views.py
from flask import Blueprint, render_template
from final_proj.views.auth_views import login_required

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
@login_required # 데코레이터 적용
def index():
    return render_template('index.html')

final_proj/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='../static/css/common.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='../static/css/index.css') }}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <title>나만의 버킷리스트</title>
</head>

<body>
    <div class="container">
        <h3><span class="highlight">{{user.nickname}}</span>님의 버킷리스트 <br /><span
                class="highlight bucklist-count"></span>개 남았어요</h3>
        <div class="bucket-create-box">
            <input type="text" placeholder="버킷리스트를 입력하세요" />
            <button type="button" id="createBtn">+</button>
        </div>
        <div class="bucket-list-box">
            <div class="bucket-list-title">
                <div class="left">버킷리스트</div>
                <div class="right">달성</div>
            </div>
            <div class="bucket-list">
                <div class="content">번지점프</div>
                <div class="checkbox">
                    <input type="checkbox" class="check" id="check1" checked /><label for="check1"></label>
                </div>
            </div>
            <div class="bucket-list">
                <div class="content">세계여행</div>
                <div class="checkbox">
                    <input type="checkbox" class="check" id="check2" /><label for="check2"></label>
                </div>
            </div>
            <div class="bucket-list">
                <div class="content">스카이다이빙</div>
                <div class="checkbox">
                    <input type="checkbox" class="check" id="check3" /><label for="check3"></label>
                </div>
            </div>
            <div class="bucket-list">
                <div class="content">교환학생</div>
                <div class="checkbox">
                    <input type="checkbox" class="check" id="check4" /><label for="check4"></label>
                </div>
            </div>
            <div class="bucket-list">
                <div class="content">워킹홀리데이</div>
                <div class="checkbox">
                    <input type="checkbox" class="check" id="check5" /><label for="check5"></label>
                </div>
            </div>
        </div>

    </div>
    <div class="footer">


        <div class="left">
            <p>2024-1 디지털콘텐츠프로그래밍 기말프로젝트</p>
            <p>1986004 김혜빈</p>
        </div>
        <div class="right">

            <button id="logoutBtn" onclick="location.href = '/auth/logout/'">로그아웃</button>
        </div>

    </div>

    <!-- js -->
    <script src="../static/js/index.js"></script>
</body>

</html>

final_proj/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='../static/css/common.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='../static/css/login.css') }}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <title>로그인</title>
    <script>
        const loginUrl = "{{ url_for('auth.login') }}";
        const mainIndexUrl = "{{ url_for('main.index') }}";
    </script>
</head>

<body>
    <div class="container">
        <h2>로그인</h2>
        <form method="post" id="loginForm" action="{{ url_for('auth.login') }}">
            <!-- CSRF protection -->
            {{ form.hidden_tag() }}
            <div class="input-box">
                <input type="text" placeholder="아이디" name="username" />
                <input type="password" placeholder="비밀번호" name="password" />
            </div>
            <div class="btn-box">
                <button type="submit" id="loginBtn">로그인</button>
                <button type="button" id="registerBtn" onclick="location.href = '../register'">회원가입</button>
            </div>
        </form>
    </div>

    <!-- js -->
    <script src="{{ url_for('static', filename='../../../static/js/login.js') }}"></script>
</body>

</html>

final_proj/templates/registeration.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입</title>
</head>

<body>
    <h1>회원가입</h1>
</body>

</html>

final_proj/templates/registration.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='../static/css/common.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='../static/css/login.css') }}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <title>회원가입</title>
    <!-- username, nickname 중복 검사 -->
    <script>
        const checkUsernameUrl = "{{ url_for('auth.check_username') }}";
        const checkNicknameUrl = "{{ url_for('auth.check_nickname') }}";
    </script>
</head>

<body>
    <div class="container">
        <h2>회원가입</h2>
        <form method="POST" action="{{ url_for('auth.register') }}">
            <!-- CSRF protection -->
            {{ form.hidden_tag() }}
            <div class="input-box">
                <input type="text" placeholder="아이디" name="username" value="{{ form.username.data or '' }}" />
                <input type="password" placeholder="비밀번호" name="password" value="{{ form.password.data or '' }}" />
                <input type="password" placeholder="비밀번호 재확인" name="confirm_password"
                    value="{{ form.confirm_password.data or '' }}" />
                <input type="text" placeholder="닉네임" name="nickname" value="{{ form.nickname.data or '' }}" />
            </div>
            <div class="btn-box">
                <button type="submit" id="loginBtn" disabled>회원가입 완료</button>
                <button type="button" id="registerBtn">로그인 페이지로 이동</button>
            </div>
        </form>
    </div>


    <!-- js -->
    <script src="{{ url_for('static', filename='../../../static/js/register.js') }}"></script>
</body>

</html>